### ISSUE TITLE
Turtlebot4 Simulator is not working

### ISSUE THREAD

**Issue by TechExplorer98** [turtlebot/turtlebot4-user-manual#20] opened 2024-04-19 07:32 UTC
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

sudo apt install ros-humble-turtlebot4-simulator

### Expected behaviour

The expected behavior is for the Gazebo simulator to launch successfully, displaying the simulation environment with the Turtlebot 4 robot model loaded, without encountering any error messages related to invalid services or busy servers.

### Actual behaviour

The actual behavior is encountering a black window in Gazebo, along with an error message indicating that the service [/gazebo/world] is not valid. After a few minutes, another message indicates that the server may be busy downloading resources, advising patience.

### Error messages

```bash
When I run the simulator with the default setting "ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py", I encounter a black window in Gazebo and in the terminal I see the error message: 
Requesting list of world names. Service [/gazebo/world] is not valid."
After a few minutes, I receive the message: 
[ruby $(which ign) gazebo-1] [Dbg] [Gui.cc.333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
```

### To Reproduce

1. Open a terminal window.
2. Run the command: `ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py`.
3. Observe the Gazebo simulator window.
4. Check the terminal for any error messages.

**Comment by tonybaltovski** [comment] 2024-04-23 01:21
This is a duplicate of https://github.com/turtlebot/turtlebot4_simulator/issues/51.  Please see there for more information.

**Closed as completed by tonybaltovski** 2024-04-23 01:21 UTC
Labels: bug
